# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iLib', '0002_auto_20160727_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='request_status',
            field=models.BooleanField(default=True),
        ),
    ]
