# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iLib', '0003_auto_20161017_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_published',
            field=models.DateField(null=True),
        ),
    ]
